### ISSUE TITLE
Add support for the missing projects endpoint

### ISSUE THREAD

**Issue by savvasdalkitsis** [Smartling/api-sdk-java#58]
There is no client for accessing the projects endpoint. I raised #57 to add such a client.

I tried to follow the same structure and formatting as the FileClient, hopefully it can be merged as is but do let me know if any changes are required

**Comment by dimitrystd** [comment]
@savvasdalkitsis Just want to let you know that i have seen your PR but don't plan accept it because we would like to keep this SDK only for Files API. I know it may sound strange why SDK with such generic name cannot contain other APIs but there are following reasons:
- We heavily use this sdk here at smartling
- We have separate small SDKs for every API (like Projects; Jobs; etc)

Unfortunately, it's not easy to share with you other SDKs because they have some internal dependencies and live in our binary repository.
I contacted ASOS's account manager about this on Fri. He researches what we can do for ASOS.

**Comment by savvasdalkitsis** [comment]
Ah no worries, I wasn't aware.

No pressure as far as asos is concerned. I initially implemented this pr in our codebase and thought I'd move it the the sdk. 

We're not blocked by anything. I'll close this pr 

👍
